<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <VersionPrefix>0.4.2</VersionPrefix>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
