<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MaxyModLoader</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../MaxyModLoader.Core/MaxyModLoader.Core.csproj" /></ItemGroup>
  <ItemGroup><Content Include="../third-party/markdig-license.txt" Link="ThirdPartyNotices.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
</Project>
