<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup><RootNamespace>MaxyModLoader</RootNamespace></PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Runtime/bootstrap.lua" />
        <EmbeddedResource Include="Runtime/manager.lua" />
        <EmbeddedResource Include="Runtime/mcp.lua" />
    </ItemGroup>

</Project>
