<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>MaxyModLoader</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <EmbeddedResource Include="Runtime/bootstrap.lua" />
        <EmbeddedResource Include="Runtime/manager.lua" />
        <EmbeddedResource Include="Runtime/markdown.lua" />
        <EmbeddedResource Include="Runtime/mcp.lua" />
        <EmbeddedResource Include="Runtime/display.lua" />
        <EmbeddedResource Include="Assets/UI/*.dds" LogicalName="MaxyModLoader.Assets.%(Filename)%(Extension)" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Markdig" Version="1.3.2" />
    </ItemGroup>

</Project>
